name: 'Send activities to RPL 3.0'
description: 'Sends modified/created files in the repository to RPL 3.0, to the corresponding activity, according to the course id in folder name'
inputs: 
  api_base_url:
    description: 'RPL 3.0 Activities API base url'
    required: false
    default: 'https://beta.myrpl.ar/activities_api'
  users_api_base_url:
    description: 'RPL 3.0 Users API base url'
    required: false
    default: 'https://beta.myrpl.ar/users_api'
  activities_dir:
    description: 'Activities directory in current repository. it defaults to "activities"'
    required: false
    default: 'activities'
  rpl_username:
    description: 'RPL 3.0 username'
    required: true
  rpl_password:
    description: 'RPL 3.0 password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x "${GITHUB_ACTION_PATH}/detect_changes.sh"
        chmod +x "${GITHUB_ACTION_PATH}/process_activities_changes.sh"

    - name: Detect activity changes
      id: detect-changes
      shell: bash
      env:
        ACTIVITIES_DIR: ${{ inputs.activities_dir }}
      run: |
        cd "$GITHUB_WORKSPACE"
        "${GITHUB_ACTION_PATH}/detect_changes.sh" > activity_changes.txt
        
        # Check if there are any changes
        if [[ -s activity_changes.txt ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Process activity changes
      if: steps.detect-changes.outputs.has_changes == 'true'
      shell: bash
      env:
        RPL_USERNAME: ${{ inputs.rpl_username }}
        RPL_PASSWORD: ${{ inputs.rpl_password }}
        ACTIVITIES_API_BASE_URL: ${{ inputs.api_base_url }}
        USERS_API_BASE_URL: ${{ inputs.users_api_base_url }}
      run: |
        cd "$GITHUB_WORKSPACE"
        cat activity_changes.txt | "${GITHUB_ACTION_PATH}/process_activities_changes.sh"
